# 배포용

server:
  forward-headers-strategy: framework
  port: 8080

spring:
  application:
    name: pillmate

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://3.27.238.242:3306/pillmate_db?allowPublicKeyRetrieval=true&sslMode=DISABLED&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&useUnicode=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword123}

    hikari:
      max-lifetime: 400000
      idle-timeout: 600000
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update # 초기 개발은 create/update 중 택1
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Seoul


# 로깅 레벨 설정: SQL을 더 자세히 보고 싶을 때 사용
logging:
  level:
    org.hibernate.SQL: debug # 실행되는 SQL 쿼리를 보여줌 (show-sql: true와 유사)
    org.hibernate.type: trace # SQL에 바인딩되는 파라미터 값을 보여줌 (매우 유용!)
    org.springframework.jdbc: debug
    org.springframework.security.oauth2: debug
    org.springframework.web.client.RestTemplate: debug
    org.springframework.security.oauth2.client: trace
    org.springframework.security.oauth2.core: trace

# Swagger(OpenAPI) 설정
springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
  api-docs:
    enabled: true

external:
  mfds:
    # 식약처 e약은요 OpenAPI 기본 URL
    base-url: https://apis.data.go.kr/1471000
    # 실행 환경에서 반드시 MFDS_SERVICE_KEY 환경 변수로 설정하세요.
    service-key: ${MFDS_SERVICE_KEY:}
